import 'car-robots-library/dist/style.css'
import '../globals.css'
import { NextIntlClientProvider, hasLocale } from 'next-intl'
import { notFound } from 'next/navigation'
import React from 'react'
import { Geist, Geist_Mono } from 'next/font/google'
import type { Metadata } from 'next'
import { routing } from '@/src/i18n/routing'
import { ClientProviders } from '@/src/app/[locale]/_clientProvider/clientProvider'
import { ToastContainer } from '@/src/shared/components/toast'
import { Header } from '@/src/shared/components/headers/Header'
import '../globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}) {
  const { locale } = await params
  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  return (
    <html
      lang={locale}
      className='no-touch'
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-dark-700`}
      >
        <NextIntlClientProvider locale={locale}>
          <Header />
          <ClientProviders>{children}</ClientProviders>
          <ToastContainer />
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
